/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-14 11:52:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.module;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class navbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"humberger__menu__overlay\"></div>\r\n");
      out.write("    <div class=\"humberger__menu__wrapper\">\r\n");
      out.write("        <div class=\"humberger__menu__logo\">\r\n");
      out.write("            <a href=\"/GivEngel/Givengel?cmd=main-page\"><img src=\"img/logo.png\" alt=\"\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"humberger__menu__cart\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-heart\"></i> <span>1</span></a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa fa-shopping-bag\"></i> <span>3</span></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"header__cart__price\">마이페이지 <span></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"humberger__menu__widget\">\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"header__top__right__auth\">\r\n");
      out.write("                <a href=\"/GivEngel/Givengel?cmd=login-page\"><i class=\"fa fa-user\"></i> Login</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"humberger__menu__nav mobile-menu\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"active\"><a href=\"/GivEngel/Givengel?cmd=main-page\">Home</a></li>\r\n");
      out.write("                <li><hr></li>\r\n");
      out.write("					<li><a href=\"#\">Products</a>\r\n");
      out.write("					<ul class=\"header__menu__dropdown\">\r\n");
      out.write("							<li><a href=\"./shop-details.html\">ALL</a></li>\r\n");
      out.write("							<li><a href=\"./shoping-cart.html\">TOP</a></li>\r\n");
      out.write("							<li><a href=\"./checkout.html\">BOTTOM</a></li>\r\n");
      out.write("							<li><a href=\"./blog-details.html\">BAG</a></li>\r\n");
      out.write("							<li><a href=\"./blog-details.html\">ACC</a></li>\r\n");
      out.write("							<li><a href=\"./blog-details.html\">SHOES</a></li>\r\n");
      out.write("							<li><hr></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li><a href=\"/GivEngel/Givengel?cmd=campaign-page\">Campaign</a></li>\r\n");
      out.write("					<li><a href=\"/GivEngel/Givengel?cmd=sponsor-page\">Sponsor</a></li>\r\n");
      out.write("					<li><a href=\"./blog.html\">Flea Market</a></li>\r\n");
      out.write("                \r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div id=\"mobile-menu-wrap\"></div>\r\n");
      out.write("        <div class=\"header__top__right__social\">\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("            <a href=\"#\"><i class=\"fa fa-pinterest-p\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"humberger__menu__contact\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><i class=\"fa fa-envelope\"></i>github.com/GIVENGEL</li>\r\n");
      out.write("                <li>멋진 상품과 후원을 동시에 - GivEngel</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	<header class=\"header\">\r\n");
      out.write("	<div class=\"header__top\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<div class=\"header__top__left\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li></a><i class=\"fa fa-envelope\"></i><a href=\"/GivEngel/Givengel?cmd=contact-page\"> GivEngel?</a></li>\r\n");
      out.write("							<li>기부와 후원으로 세상을 밝게 만드세요.</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<div class=\"header__top__right\">\r\n");
      out.write("						<div class=\"header__top__right__social\">\r\n");
      out.write("							<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- 로그인 섹션 --------------------------------------------- -->\r\n");
      out.write("						<div class=\"header__top__right__auth\">\r\n");
      out.write("							<a href=\"/GivEngel/Givengel?cmd=login-page\"><i\r\n");
      out.write("								class=\"fa fa-user\"></i> Login</a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--  nav bar 시작 -->\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-3\">\r\n");
      out.write("				<div class=\"header__logo\">\r\n");
      out.write("					<a href=\"/GivEngel/Givengel?cmd=main-page\"><img src=\"img/logo.png\" alt=\"\"></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-lg-9\">\r\n");
      out.write("				<nav class=\"header__menu\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li class=\"active\"><a href=\"/GivEngel/Givengel?cmd=main-page\">Home</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<li><a href=\"#\">Products</a>\r\n");
      out.write("					<ul class=\"header__menu__dropdown\">\r\n");
      out.write("							<li><a href=\"./shoping-cart.html\">TOP</a></li>\r\n");
      out.write("							<li><a href=\"./checkout.html\">BOTTOM</a></li>\r\n");
      out.write("							<li><a href=\"./blog-details.html\">BAG</a></li>\r\n");
      out.write("							<li><a href=\"./blog-details.html\">ACC</a></li>\r\n");
      out.write("							<li><a href=\"./blog-details.html\">SHOES</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li><a href=\"/GivEngel/Givengel?cmd=campaign-page\">Campaign</a></li>\r\n");
      out.write("					<li><a href=\"/GivEngel/Givengel?cmd=sponsor-page\">Sponsor</a></li>\r\n");
      out.write("					<li><a href=\"./blog.html\">Flea Market</a></li>\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("				</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		<div class=\"humberger__open\">\r\n");
      out.write("			<i class=\"fa fa-bars\"></i>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
