/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-13 10:48:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class campaignView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"Ogani Template\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"Ogani, unica, creative, html\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Ogani | Template</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Font -->\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Css Styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/nice-select.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/jquery-ui.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Page Preloder -->\r\n");
      out.write("    <div id=\"preloder\">\r\n");
      out.write("        <div class=\"loader\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!--  navbar &  side over wrap -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "module/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "module/sideCategory.jsp", out, false);
      out.write("\r\n");
      out.write("   \r\n");
      out.write("	\r\n");
      out.write("    !-- Blog Details Hero Begin -->\r\n");
      out.write("    <section class=\"blog-details-hero set-bg\" data-setbg=\"img/blog/details/details-hero.jpg\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"blog__details__hero__text\">\r\n");
      out.write("                        <h2>Select 로 받아온 후원 단체 이름 넣기</h2>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>총 누적 금액</li>\r\n");
      out.write("                            <li>후원 만료일</li>\r\n");
      out.write("                            <li>댓글 수</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Blog Details Hero End -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Blog Details Section Begin -->\r\n");
      out.write("    <section class=\"blog-details spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-5 order-md-1 order-2\">\r\n");
      out.write("                    <div class=\"blog__sidebar\">\r\n");
      out.write("                        <div class=\"blog__sidebar__search\">\r\n");
      out.write("                            <form action=\"#\">\r\n");
      out.write("                                <input type=\"text\" placeholder=\"상품 검색하기\">\r\n");
      out.write("                                <button type=\"submit\"><span class=\"icon_search\"></span></button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog__sidebar__item\">\r\n");
      out.write("                            <h4>Categories</h4>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"#\">전체 상품 이동</a></li>\r\n");
      out.write("                                <li><a href=\"#\">WHERE ? 카테고리 별 이동1</a></li>\r\n");
      out.write("                                <li><a href=\"#\">WHERE ? 카테고리 별 이동2</a></li>\r\n");
      out.write("                                <li><a href=\"#\">WHERE ? 카테고리 별 이동3</a></li>\r\n");
      out.write("                                <li><a href=\"#\">WHERE ? 카테고리 별 이동4</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog__sidebar__item\">\r\n");
      out.write("                            <h4>다른 후원 글</h4>\r\n");
      out.write("                            <div class=\"blog__sidebar__recent\">\r\n");
      out.write("                                <a href=\"#\" class=\"blog__sidebar__recent__item\">\r\n");
      out.write("                                    <div class=\"blog__sidebar__recent__item__pic\">\r\n");
      out.write("                                        <img src=\"img/blog/sidebar/sr-1.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"blog__sidebar__recent__item__text\">\r\n");
      out.write("                                        <h6>다른 후원 글1<br />총 후원금액</h6>\r\n");
      out.write("                                        <span>~만료날짜</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"blog__sidebar__recent__item\">\r\n");
      out.write("                                    <div class=\"blog__sidebar__recent__item__pic\">\r\n");
      out.write("                                        <img src=\"img/blog/sidebar/sr-1.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"blog__sidebar__recent__item__text\">\r\n");
      out.write("                                        <h6>다른 후원 글2<br />총 후원금액</h6>\r\n");
      out.write("                                        <span>~만료날짜</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"blog__sidebar__recent__item\">\r\n");
      out.write("                                    <div class=\"blog__sidebar__recent__item__pic\">\r\n");
      out.write("                                        <img src=\"img/blog/sidebar/sr-1.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"blog__sidebar__recent__item__text\">\r\n");
      out.write("                                        <h6>다른 후원 글3<br />총 후원금액</h6>\r\n");
      out.write("                                        <span>~만료날짜</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog__sidebar__item\">\r\n");
      out.write("                            <h4>태그 별 검색</h4>\r\n");
      out.write("                            <div class=\"blog__sidebar__item__tags\">\r\n");
      out.write("                                <a href=\"#\">신발</a>\r\n");
      out.write("                                <a href=\"#\">할인중</a>\r\n");
      out.write("                                <a href=\"#\">악세사리</a>\r\n");
      out.write("                                <a href=\"#\">여름</a>\r\n");
      out.write("                                <a href=\"#\">가방</a>\r\n");
      out.write("                                <a href=\"#\">특정 후원단체 물품</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-8 col-md-7 order-md-1 order-1\">\r\n");
      out.write("                    <div class=\"blog__details__text\">\r\n");
      out.write("                        <img src=\"img/blog/details/details-pic.jpg\" alt=\"\">\r\n");
      out.write("                        <p>대충 해당 후원단체에 대한 설명 데이터베이스에서 가져오기</p>\r\n");
      out.write("                        <hr/>\r\n");
      out.write("                        <h3>후원 하기 </h3>\r\n");
      out.write("                        <p>대충 후원은 어떤 사회적 발전을 가져오는지 설명하는 GivEngel 가이드 불라불라</p>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control mb-4\" name=\"id\"\r\n");
      out.write("													placeholder=\"후원 금액을 입력하세요!\">\r\n");
      out.write("                        <button type=\"button\" name=\"donation\"\r\n");
      out.write("											class=\"btn btn-block btn-success\" style=\"height:150px\"><spaa class=\"display-4\">후원하기!</spaa></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"blog__details__content\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-6\">\r\n");
      out.write("                                <div class=\"blog__details__author\">\r\n");
      out.write("                                    <div class=\"blog__details__author__pic\">\r\n");
      out.write("                                        <img src=\"img/blog/details/details-author.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"blog__details__author__text\">\r\n");
      out.write("                                        <h6>GivEngel 이미지 사진 넣기</h6>\r\n");
      out.write("                                        <span>Admin</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-6\">\r\n");
      out.write("                                <div class=\"blog__details__widget\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><span>Categories:</span> Campaign</li>\r\n");
      out.write("                                        <li><span>Tags:</span> 태그 내용 넣기</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                    <div class=\"blog__details__social\">\r\n");
      out.write("                                        <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                                        <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                                        <a href=\"#\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("                                        <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                                        <a href=\"#\"><i class=\"fa fa-envelope\"></i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Blog Details Section End -->\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("     ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "module/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"js/mixitup.min.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
