/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-10 09:00:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"description\" content=\"Ogani Template\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"Ogani, unica, creative, html\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Ogani | Template</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Font -->\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Css Styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/nice-select.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/jquery-ui.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Page Preloder -->\r\n");
      out.write("    <div id=\"preloder\">\r\n");
      out.write("        <div class=\"loader\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!--  navbar &  side over wrap -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "module/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <!-- 사이드 카테고리  -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "module/sideCategory.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    <!-- Categories Section Begin -->\r\n");
      out.write("    <section class=\"categories\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"categories__slider owl-carousel\">\r\n");
      out.write("                    <div class=\"col-lg-3\">\r\n");
      out.write("                        <div class=\"categories__item set-bg\" data-setbg=\"img/categories/cat-1.jpg\">\r\n");
      out.write("                            <h5><a href=\"#\">양키 캔들</a></h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3\">\r\n");
      out.write("                        <div class=\"categories__item set-bg\" data-setbg=\"img/categories/cat-2.jpg\">\r\n");
      out.write("                            <h5><a href=\"#\">도자기 공예</a></h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3\">\r\n");
      out.write("                        <div class=\"categories__item set-bg\" data-setbg=\"img/categories/cat-3.jpg\">\r\n");
      out.write("                            <h5><a href=\"#\">원예</a></h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3\">\r\n");
      out.write("                        <div class=\"categories__item set-bg\" data-setbg=\"img/categories/cat-4.jpg\">\r\n");
      out.write("                            <h5><a href=\"#\">수제 비누</a></h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3\">\r\n");
      out.write("                        <div class=\"categories__item set-bg\" data-setbg=\"img/categories/cat-5.jpg\">\r\n");
      out.write("                            <h5><a href=\"#\">악세사리</a></h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Categories Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Featured Section Begin -->\r\n");
      out.write("    <section class=\"featured spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"section-title\">\r\n");
      out.write("                        <h2>가장 많이 찾는 물품</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"featured__controls\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li class=\"active\" data-filter=\"*\">전체</li>\r\n");
      out.write("                            <li data-filter=\".sale\">할인중</li>\r\n");
      out.write("                            <li data-filter=\".hot\">인기 상품</li>\r\n");
      out.write("                            <li data-filter=\".gift\">사은품 증정</li>\r\n");
      out.write("                            <li data-filter=\".high\">알찬 기부</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row featured__filter\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6 mix hot sale\">\r\n");
      out.write("                    <div class=\"featured__item\">\r\n");
      out.write("                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-1.jpg\">\r\n");
      out.write("                            <ul class=\"featured__item__pic__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"featured__item__text\">\r\n");
      out.write("                            <h6><a href=\"#\">수공 원예 화분</a></h6>\r\n");
      out.write("                            <h5 style=\"color: red;\">24,000원(-20%)</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6 mix gift high\">\r\n");
      out.write("                    <div class=\"featured__item\">\r\n");
      out.write("                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-2.jpg\">\r\n");
      out.write("                            <ul class=\"featured__item__pic__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"featured__item__text\">\r\n");
      out.write("                            <h6><a href=\"#\">수공 가죽 파우치+기부뱃지</a></h6>\r\n");
      out.write("                            <h5>55,000원</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6 mix hot high\">\r\n");
      out.write("                    <div class=\"featured__item\">\r\n");
      out.write("                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-3.jpg\">\r\n");
      out.write("                            <ul class=\"featured__item__pic__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"featured__item__text\">\r\n");
      out.write("                            <h6><a href=\"#\">버튼 홀더</a></h6>\r\n");
      out.write("                            <h5>5,000원</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6 mix sale gift\">\r\n");
      out.write("                    <div class=\"featured__item\">\r\n");
      out.write("                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-4.jpg\">\r\n");
      out.write("                            <ul class=\"featured__item__pic__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"featured__item__text\">\r\n");
      out.write("                            <h6><a href=\"#\">유기농 조미료 세트+덤증정</a></h6>\r\n");
      out.write("                            <h5 style=\"color: red;\">45,000원(-10%)</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6 mix gift high\">\r\n");
      out.write("                    <div class=\"featured__item\">\r\n");
      out.write("                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-5.jpg\">\r\n");
      out.write("                            <ul class=\"featured__item__pic__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"featured__item__text\">\r\n");
      out.write("                            <h6><a href=\"#\">패럴림픽 후원 패키지</a></h6>\r\n");
      out.write("                            <h5>50,000원</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6 mix sale hot\">\r\n");
      out.write("                    <div class=\"featured__item\">\r\n");
      out.write("                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-6.jpg\">\r\n");
      out.write("                            <ul class=\"featured__item__pic__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"featured__item__text\">\r\n");
      out.write("                            <h6><a href=\"#\">수제 천연 비누</a></h6>\r\n");
      out.write("                            <h5 style=\"color: red;\">8,000원(-20%)</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6 mix high hot\">\r\n");
      out.write("                    <div class=\"featured__item\">\r\n");
      out.write("                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-7.jpg\">\r\n");
      out.write("                            <ul class=\"featured__item__pic__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"featured__item__text\">\r\n");
      out.write("                            <h6><a href=\"#\">희망을 그린 그림</a></h6>\r\n");
      out.write("                            <h5 >20,000원</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-4 col-sm-6 mix hot high\">\r\n");
      out.write("                    <div class=\"featured__item\">\r\n");
      out.write("                        <div class=\"featured__item__pic set-bg\" data-setbg=\"img/featured/feature-8.jpg\">\r\n");
      out.write("                            <ul class=\"featured__item__pic__hover\">\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-heart\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-retweet\"></i></a></li>\r\n");
      out.write("                                <li><a href=\"#\"><i class=\"fa fa-shopping-cart\"></i></a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"featured__item__text\">\r\n");
      out.write("                            <h6><a href=\"#\">수제 캔들</a></h6>\r\n");
      out.write("                            <h5>12,000원</h5>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Featured Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Banner Begin -->\r\n");
      out.write("    \r\n");
      out.write("    <!-- Banner End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Latest Product Section Begin -->\r\n");
      out.write("    <section class=\"latest-product spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"latest-product__text\">\r\n");
      out.write("                        <h4>최신 상품</h4>\r\n");
      out.write("                        <div class=\"latest-product__slider owl-carousel\">\r\n");
      out.write("                            <div class=\"latest-prdouct__slider__item\">\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"latest-prdouct__slider__item\">\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"latest-product__text\">\r\n");
      out.write("                        <h4>최고 인기 상품</h4>\r\n");
      out.write("                        <div class=\"latest-product__slider owl-carousel\">\r\n");
      out.write("                            <div class=\"latest-prdouct__slider__item\">\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"latest-prdouct__slider__item\">\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("                    <div class=\"latest-product__text\">\r\n");
      out.write("                        <h4>리뷰 상품</h4>\r\n");
      out.write("                        <div class=\"latest-product__slider owl-carousel\">\r\n");
      out.write("                            <div class=\"latest-prdouct__slider__item\">\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"latest-prdouct__slider__item\">\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"latest-product__item\">\r\n");
      out.write("                                    <div class=\"latest-product__item__pic\">\r\n");
      out.write("                                        <img src=\"img/latest-product/prepare.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"latest-product__item__text\">\r\n");
      out.write("                                        <h6>준비중입니다</h6>\r\n");
      out.write("                                        <span>-원</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Latest Product Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Blog Section Begin -->\r\n");
      out.write("    <section class=\"from-blog spad\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"section-title from-blog__title\">\r\n");
      out.write("                        <h2>블로그 글 소개</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("                    <div class=\"blog__item\">\r\n");
      out.write("                        <div class=\"blog__item__pic\">\r\n");
      out.write("                            <img src=\"img/blog/blog-1.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog__item__text\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><i class=\"fa fa-calendar-o\"></i> May 4,2019</li>\r\n");
      out.write("                                <li><i class=\"fa fa-comment-o\"></i> 5</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h5><a href=\"#\">도쿄올림픽, 패럴림픽 개최 중단..?</a></h5>\r\n");
      out.write("                            <p>올림픽의 마지막을 장식하는 패럴림픽, 그런데 다음 올릭픽에서는 개최가 안될지 모른다고..? </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("                    <div class=\"blog__item\">\r\n");
      out.write("                        <div class=\"blog__item__pic\">\r\n");
      out.write("                            <img src=\"img/blog/blog-2.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog__item__text\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><i class=\"fa fa-calendar-o\"></i> May 4,2019</li>\r\n");
      out.write("                                <li><i class=\"fa fa-comment-o\"></i> 5</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h5><a href=\"#\">고양이, 그리고 불편한 진실</a></h5>\r\n");
      out.write("                            <p>인간만이 신체적 결함에 부조리함을 느낀다고 생각하시나요? 고양이 로소의 이야기를 들어보세요. </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("                    <div class=\"blog__item\">\r\n");
      out.write("                        <div class=\"blog__item__pic\">\r\n");
      out.write("                            <img src=\"img/blog/blog-3.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"blog__item__text\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><i class=\"fa fa-calendar-o\"></i> May 4,2019</li>\r\n");
      out.write("                                <li><i class=\"fa fa-comment-o\"></i> 5</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            <h5><a href=\"#\">지구 한 바퀴를 돌고 와도 변치않는 우정</a></h5>\r\n");
      out.write("                            <p>영국에 사는 두 소녀의 드라마같은 우정이야기 </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Blog Section End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("     ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "module/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"js/mixitup.min.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
