/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-10 08:07:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinForm_002cjsp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"description\" content=\"Ogani Template\">\r\n");
      out.write("<meta name=\"keywords\" content=\"Ogani, unica, creative, html\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Ogani | Template</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Google Font -->\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Css Styles -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/nice-select.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery-ui.min.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Page Preloder -->\r\n");
      out.write("	<div id=\"preloder\">\r\n");
      out.write("		<div class=\"loader\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Humberger Begin -->\r\n");
      out.write("	<div class=\"humberger__menu__overlay\"></div>\r\n");
      out.write("	<div class=\"humberger__menu__wrapper\">\r\n");
      out.write("		<div class=\"humberger__menu__logo\">\r\n");
      out.write("			<a href=\"#\"><img src=\"img/logo.png\" alt=\"\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"humberger__menu__cart\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"#\"><i class=\"fa fa-heart\"></i> <span>1</span></a></li>\r\n");
      out.write("				<li><a href=\"#\"><i class=\"fa fa-shopping-bag\"></i> <span>3</span></a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div class=\"header__cart__price\">\r\n");
      out.write("				장바구니: <span>$150.00</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"humberger__menu__widget\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"header__top__right__auth\">\r\n");
      out.write("				<a href=\"#\"><i class=\"fa fa-user\"></i> Login</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<nav class=\"humberger__menu__nav mobile-menu\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li class=\"active\"><a href=\"./index.html\">Home</a></li>\r\n");
      out.write("				<li><a href=\"./shop-grid.html\">상품</a></li>\r\n");
      out.write("				<li><a href=\"#\">카테고리</a>\r\n");
      out.write("					<ul class=\"header__menu__dropdown\">\r\n");
      out.write("						<li><a href=\"./shop-details.html\">시각장애 후원 상품</a></li>\r\n");
      out.write("						<li><a href=\"./shoping-cart.html\">청각장애 후원 상품</a></li>\r\n");
      out.write("						<li><a href=\"./checkout.html\">그린피스 후원 상품</a></li>\r\n");
      out.write("						<li><a href=\"./blog-details.html\">굿네이버스 상품</a></li>\r\n");
      out.write("					</ul></li>\r\n");
      out.write("				<li><a href=\"./blog.html\">블로그 방문하기</a></li>\r\n");
      out.write("				<li><a href=\"./contact.html\">상담</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<div id=\"mobile-menu-wrap\"></div>\r\n");
      out.write("		<div class=\"header__top__right__social\">\r\n");
      out.write("			<a href=\"#\"><i class=\"fa fa-facebook\"></i></a> <a href=\"#\"><i\r\n");
      out.write("				class=\"fa fa-twitter\"></i></a> <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("			<a href=\"#\"><i class=\"fa fa-pinterest-p\"></i></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"humberger__menu__contact\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><i class=\"fa fa-envelope\"></i>github.com/GIVENGEL</li>\r\n");
      out.write("				<li>멋진 상품과 후원을 동시에 - GivEngel</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Humberger End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Header Section Begin -->\r\n");
      out.write("	<header class=\"header\">\r\n");
      out.write("		<div class=\"header__top\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-lg-6\">\r\n");
      out.write("						<div class=\"header__top__left\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><i class=\"fa fa-envelope\"></i> Givengel.com</li>\r\n");
      out.write("								<li>기부와 후원으로 세상을 밝게 만드세요.</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-6\">\r\n");
      out.write("						<div class=\"header__top__right\">\r\n");
      out.write("							<div class=\"header__top__right__social\">\r\n");
      out.write("								<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"header__top__right__auth\">\r\n");
      out.write("								<a href=\"#\"><i class=\"fa fa-user\"></i> Login</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-3\">\r\n");
      out.write("					<div class=\"header__logo\">\r\n");
      out.write("						<a href=\"./index.html\"><img src=\"img/logo.png\" alt=\"\"></a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<nav class=\"header__menu\">\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li class=\"active\"><a href=\"./index.html\">Home</a></li>\r\n");
      out.write("							<li><a href=\"./shop-grid.html\">상품</a></li>\r\n");
      out.write("							<li><a href=\"#\">카테고리</a>\r\n");
      out.write("								<ul class=\"header__menu__dropdown\">\r\n");
      out.write("									<li><a href=\"./shop-details.html\">시각장애 후원 상품</a></li>\r\n");
      out.write("									<li><a href=\"./shoping-cart.html\">청각장애 후원 상품</a></li>\r\n");
      out.write("									<li><a href=\"./checkout.html\">그린피스 후원 상품</a></li>\r\n");
      out.write("									<li><a href=\"./blog-details.html\">굿네이버스 상품</a></li>\r\n");
      out.write("								</ul></li>\r\n");
      out.write("							<li><a href=\"./blog.html\">블로그</a></li>\r\n");
      out.write("							<li><a href=\"./contact.html\">상담</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</nav>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-3\">\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"humberger__open\">\r\n");
      out.write("				<i class=\"fa fa-bars\"></i>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- Header Section End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Hero Section Begin -->\r\n");
      out.write("	<section class=\"hero\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<label class=\"display-4 text-center\">Welcome to GivEngel</label>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div >\r\n");
      out.write("							<section class=\"container\">\r\n");
      out.write("								<section class=\"login-form\">\r\n");
      out.write("									<form method=\"post\" action=\"\" role=\"login\">\r\n");
      out.write("										<h2>로그인</h2>\r\n");
      out.write("										<p>등록하신 계정을 입력하세요.</p>\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"input-group\">\r\n");
      out.write("												<div class=\"input-group-addon\">\r\n");
      out.write("													<span class=\"text-primary glyphicon glyphicon-envelope\"></span>\r\n");
      out.write("												</div>\r\n");
      out.write("												<input type=\"email\" name=\"email\" placeholder=\"이메일 아이디\"\r\n");
      out.write("													required class=\"form-control\" />\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"form-group\">\r\n");
      out.write("											<div class=\"input-group\">\r\n");
      out.write("												<div class=\"input-group-addon\">\r\n");
      out.write("													<span class=\"text-primary glyphicon glyphicon-lock\"></span>\r\n");
      out.write("												</div>\r\n");
      out.write("												<input type=\"password\" name=\"password\" placeholder=\"비밀번호\"\r\n");
      out.write("													required class=\"form-control\" />\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										<button type=\"submit\" name=\"go\"\r\n");
      out.write("											class=\"btn btn-block btn-success\">Sign in</button>\r\n");
      out.write("										<a href=\"#\" class=\"btn btn-block btn-default\">계정을 잊어버리셨나요?</a>\r\n");
      out.write("										<a href=\"#\" class=\"btn btn-block btn-default\">GivEngel\r\n");
      out.write("											가입하기</a>\r\n");
      out.write("									</form>\r\n");
      out.write("								</section>\r\n");
      out.write("							</section>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-6\">\r\n");
      out.write("				<img class=\"hidden-xs hidden-sm\" src=\"img/login.jpg\" alt=\"\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- Hero Section End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer Section Begin -->\r\n");
      out.write("	<footer class=\"footer spad\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-3 col-md-6 col-sm-6\">\r\n");
      out.write("					<div class=\"footer__about\">\r\n");
      out.write("						<div class=\"footer__about__logo\">\r\n");
      out.write("							<a href=\"./index.html\"><img src=\"img/logo.png\" alt=\"\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li>주소 : 대한민국 서울특별시 금천구 가산디지털로 123</li>\r\n");
      out.write("							<li>연락처 : 82+ 010-9159-5358</li>\r\n");
      out.write("							<li>이메일: github.com/GIVENGEL</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6 col-sm-6 offset-lg-1\">\r\n");
      out.write("					<div class=\"footer__widget\">\r\n");
      out.write("						<h6>프로젝트 설명</h6>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\">팀원 설명</a></li>\r\n");
      out.write("							<li><a href=\"#\"></a>:D</li>\r\n");
      out.write("							<li><a href=\"#\">프로젝트 설계</a></li>\r\n");
      out.write("							<li><a href=\"#\">프로젝트 개발과정</a></li>\r\n");
      out.write("							<li><a href=\"#\">프로젝트 후기</a></li>\r\n");
      out.write("							<li><a href=\"#\">자료실</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"#\">김승철 편이슬</a></li>\r\n");
      out.write("							<li><a href=\"#\">김인철 김민주</a></li>\r\n");
      out.write("							<li><a href=\"#\">찢었죠</a></li>\r\n");
      out.write("							<li><a href=\"#\">잠못잤죠</a></li>\r\n");
      out.write("							<li><a href=\"#\">힘들었죠</a></li>\r\n");
      out.write("							<li><a href=\"#\">깃허브에 있죠</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4 col-md-12\">\r\n");
      out.write("					<div class=\"footer__widget\">\r\n");
      out.write("						<h6>저희 깃허브 Organization 에 놀러오세요!</h6>\r\n");
      out.write("						<p>GivEngel 프로젝트를 성공적으로 마치..겠죠?</p>\r\n");
      out.write("						<form action=\"#\">\r\n");
      out.write("							<input type=\"text\" placeholder=\"Enter your Message\">\r\n");
      out.write("							<button type=\"submit\" class=\"site-btn\">메시지 보내기</button>\r\n");
      out.write("						</form>\r\n");
      out.write("						<div class=\"footer__widget__social\">\r\n");
      out.write("							<a href=\"#\"><i class=\"fa fa-facebook\"></i></a> <a href=\"#\"><i\r\n");
      out.write("								class=\"fa fa-instagram\"></i></a> <a href=\"#\"><i\r\n");
      out.write("								class=\"fa fa-twitter\"></i></a> <a href=\"#\"><i\r\n");
      out.write("								class=\"fa fa-pinterest\"></i></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"footer__copyright\">\r\n");
      out.write("						<div class=\"footer__copyright__text\">\r\n");
      out.write("							<p>\r\n");
      out.write("								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("								Copyright &copy;\r\n");
      out.write("								<script>document.write(new Date().getFullYear());</script>\r\n");
      out.write("								All rights reserved | This template is made with <i\r\n");
      out.write("									class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("									href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("								<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"footer__copyright__payment\">\r\n");
      out.write("							<img src=\"img/payment-item.png\" alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- Footer Section End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Js Plugins -->\r\n");
      out.write("	<script src=\"js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("	<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("	<script src=\"js/jquery-ui.min.js\"></script>\r\n");
      out.write("	<script src=\"js/jquery.slicknav.js\"></script>\r\n");
      out.write("	<script src=\"js/mixitup.min.js\"></script>\r\n");
      out.write("	<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
